name: web-app-check

on:

push:

branches:

- main

jobs:

test-job:

    runs-on: ubuntu-latest

    name: baic-web-app

    steps:

    - uses: actions/checkout@v3

    - uses: bahmutov/npm-install@v1

    - run: npm run lint (Run ESLint)

    - run: npm run test (Run Jest)
